add work type
stewkk/iu9lab pull request #1
Opened 2022-02-26 22:15 UTC by geogreck

2022-02-27 09:28 UTC, stewkk requested changes
@geogreck
- [x] Нужно добавить соответствующие изменения в latex-шаблон
- [ ] Обновить информацию о шаблонах в README
- [ ] Сделать так, чтобы знак № добавлялся к номеру работы, если он непустой

2022-02-28 07:49 UTC, geogreck commented
- [X] Нужно добавить соответствующие изменения в latex-шаблон
- [X] Обновить информацию о шаблонах в README
- [ ] Сделать так, чтобы знак № добавлялся к номеру работы, если он непустой

2022-02-28 08:09 UTC, stewkk approved these changes

2022-02-28 08:11 UTC, merged

2022-02-28 08:12 UTC, stewkk commented
Спасибо. Успехов!